SISPR/Controllers/CheckUTPExcelController.cs
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using SISPR.Models.ModelsUTP;
using SISPR.Controllers.Classes.CheckUTPExcelController;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Http;
using SISPR.Models;



namespace SISPR.Controllers
{
    public class CheckUTPExcelController : Controller
    {
        List<ModelVrem> propUTP = new List<ModelVrem>();
        public IActionResult Index()
        {
            return View("UploadFile");
        }


        //public IActionResult SaveOnChange(int ID, int Type, float Value)
        //{

        //    return Json("Изменения внесены!");
        //}

        public bool СontainsUTP(ExcelWorksheet Worksheet)
        {
            foreach (var cell in Worksheet.Cells)
            {
                string text = Regex.Replace(cell.Text.ToString().ToUpper(), @"^[a-zA-Z]+$",string.Empty);
               if (text == "ТИПОВОЙ УЧЕБНЫЙ ПЛАН")
                {
                    return true;
                    
                }
            }

            return false;
        }


        public async Task<IActionResult> AddUTP(IFormFile upload)
        {
            UploadFileController uploadFile = new UploadFileController();
           
           
            return View("~/Views/UTP/CheckUTPExcel/UTPViews.cshtml", CheckExcel(Directory.GetCurrentDirectory() + await uploadFile.AddFile(upload)));
        }

        public UTP CheckExcel(string path)
        {
           
            UTP uTP = new UTP();


            List<TableModel> listTable = new List<TableModel>();


            using (var pck = new OfficeOpenXml.ExcelPackage())
            {
                FileInfo existingFile = new FileInfo(path);
                //uTP.propertyUTP.Name 
                using (ExcelPackage package = new ExcelPackage(existingFile))
                {
                    foreach (ExcelWorksheet worksheet in package.Workbook.Worksheets)
                    //get the first worksheet in the workbook
                    {
                        if (СontainsUTP(worksheet))
                        {
                            uTP.propertyUTP = PropertyFill(worksheet);

                            var colRow = worksheet.Dimension.End.Row;
                            var Table = InfoTable(worksheet, colRow);
                            listTable.Add(Table);
                        }
                    }
                }
            }
                     
            

            //WorkPropertyUTP workProperty = new WorkPropertyUTP();
           
            uTP.table=listTable;

              return  uTP;

            
          
        }

        private PropertyUTP PropertyFill(ExcelWorksheet Worksheet)
        {
            PropertyUTP propertyUTP = new PropertyUTP();
            var xz = Worksheet.Cells.ToArray();
            int index = 0;
            foreach (var cell in xz)
            {
                
                if (Regex.Replace(cell.Text.ToString().ToUpper(), "[^а-яА-Я]", string.Empty) == Regex.Replace("Количество слушателей в группе:".ToUpper(), "[^а-яА-Я]", string.Empty) )
                {
                    propertyUTP.Kol_slushatel_v_group =int.Parse( xz[index+1].Text);
;
                }
                if (Regex.Replace(cell.Text.ToString().ToUpper(), "[^а-яА-Я]", string.Empty) == Regex.Replace("Количество групп".ToUpper(), "[^а-яА-Я]", string.Empty))
                {
                    propertyUTP.Kol_groups = int.Parse(xz[index + 1].Text);
                    
                }
                if (Regex.Replace(cell.Text.ToString().ToUpper(), "[^а-яА-Я]", string.Empty) == Regex.Replace("Форма обучения".ToUpper(), "[^а-яА-Я]", string.Empty))
                {
                    propertyUTP.Forma_obuchen = xz[index + 1].Text;
                    
                }
                if (Regex.Replace(cell.Text.ToString().ToUpper(), "[^а-яА-Я]", string.Empty) == Regex.Replace("Режим занятий".ToUpper(), "[^а-яА-Я]", string.Empty))
                {
                    propertyUTP.Rejim_zanyati = int.Parse(Regex.Replace(xz[index + 1].Text.ToString().ToUpper(), "[^0-9]", string.Empty));
                    
                }
                //if (Regex.Replace(cell.Text.ToString().ToUpper(), "[^а-яА-Я]", string.Empty) == Regex.Replace("Количество слушателей в группе:".ToUpper(), "[^а-яА-Я]", string.Empty))
                //{
                //    propertyUTP.Kol_slushatel_v_group = int.Parse(xz[index + 1].Text);


                //}


                if (cell.Text == "Вид учебной работы" || cell.Text == "Вид учебной нагрузки")
                {
                    break;


                }




                index++;
            }

            return propertyUTP;
        }



        public class ModelVrem
        {
          public  string str1 { get; set; }
            public string str2 { get; set; }
        }
        public TableModel InfoTable(ExcelWorksheet sheet, int colRow)
        {



            TableModel Table = new TableModel();
            int endTable = 0;
            int startTable = 0;
            bool startTableBool = false;
            bool endTableBool = false;


            for (int i = colRow; i > 0; i--)
            {
                if (sheet.Cells[i, 1].Text == "Итого часов по УТП:" && endTable == 0)
                {

                    startTable = i;
                    startTableBool = true;
                }

                if (endTableBool == true)
                {
                    propUTP.Add(new ModelVrem { str1 = sheet.Cells[i, 1].Text, str2 = sheet.Cells[i, 2].Text });
                }
                if (sheet.Cells[i, 1].Text == "Вид учебной работы" || sheet.Cells[i, 1].Text == "Вид учебной нагрузки")
                {
                    endTable = i;
                    startTableBool = false;
                    endTableBool = true;


                }



                    if (startTableBool == true)
                {



                    var row = sheet;
                    endTable = i;



                    RowTableModel NewRow = new RowTableModel();
                    NewRow.NameTypeTrainingLoad = sheet.Cells[i, 1].Text;

                    NewRow.NumberControlForms = float.Parse(sheet.Cells[i, 5].Text != "" ? sheet.Cells[i, 5].Text : "0");
                    NewRow.NumberGroups = float.Parse(sheet.Cells[i, 3].Text != "" ? sheet.Cells[i, 3].Text : "0");
                    NewRow.NumberHours = float.Parse(sheet.Cells[i, 2].Text != "" ? sheet.Cells[i, 2].Text : "0");
                    NewRow.NumberListeners = float.Parse(sheet.Cells[i, 6].Text != "" ? sheet.Cells[i, 6].Text : "0");
                    NewRow.NumberSubgroups = float.Parse(sheet.Cells[i, 4].Text != "" ? sheet.Cells[i, 4].Text : "0");
                    NewRow.VolumeHours = float.Parse(sheet.Cells[i, 7].Text != "" ? sheet.Cells[i, 7].Text : "0");

                    if (NewRow.NumberHours != 0 && NewRow.VolumeHours == 0 && TypeTrainingLoad(NewRow.NameTypeTrainingLoad) != 0)
                    {
                        NewRow.Type = 3;

                    }

                    else
                        NewRow.Type = TypeTrainingLoad(NewRow.NameTypeTrainingLoad);



                    if (NewRow.VolumeHours != 0)
                    {
                        if (((NewRow.NumberHours == 0 ? 1 : NewRow.NumberHours) * (NewRow.NumberGroups == 0 ? 1 : NewRow.NumberGroups) * (NewRow.NumberSubgroups == 0 ? 1 : NewRow.NumberSubgroups) * (NewRow.NumberControlForms == 0 ? 1 : NewRow.NumberControlForms) * (NewRow.NumberListeners == 0 ? 1 : NewRow.NumberListeners)) != NewRow.VolumeHours)
                        {
                            NewRow.Status = "неверно";
                        }
                    }





                    Table.Add(NewRow);
                }
            }
            Table.Row.Reverse();
            int j = 0;
            foreach (var row in Table.Row)
            {
                row.ID = j;
                j++;
            }

            return Table;
        }


        public int TypeTrainingLoad(string NameTypeTrainingLoad)
        {
            List<string> Auditor = new List<string>() {"лекции",
"практическиезанятия",
"проведениегрупповыхконсультацийврамкахдпппк",
"проведениедиагностических,контрольныхработ,тестирование",
"итоговаяаттестация(защитапроектов,предусмотренныхучебнымпланом,обработкарезультатовтестированияидр.,всоответствиисуп)",
"итоговаяаттестация(приемписьменныхзачетныхработ,предусмотренныхучебнымпланом)",
"приёмэкзаменов,предусмотренныхучебнымпланом",
"участиевработеитоговойаттестационнойкомиссии",
"проведениевебинаров,видеоконференцийит.п.длядистанционногообучения"
 };
            List<string> VneAuditor = new List<string>() { "разработкановыхлекционныхматериаловиумк(дляочногообучения)конспектов,дидактическогоматериаладлялекционныхипрактическихзанятий",
"разработкаучебно-методическихматериаловдлядистанционногообучения(длязаочногообучения)",
"разработкадиагностическихматериалов(входной,промежуточной,выходнойдиагностики)",
"проверкавходнойи/иливыходнойдиагностикиуровняпредметнойготовностислушателей,подготовкааналитическойсправки",
"разработкаконтрольныхзаданийкзачету",
"разработкаэкзаменационныхматериалов",
"подготовкаматериаловпрезентационногохарактеравэлектронномвиде",
"организацияисопровождениефорумов,индивидуальныхконсультацийпридистанционномобучении(заочногообучения)",
"организационноеруководствокурсами",
"учебно-методическоеруководство",
"организационноесопровождениедистанционногообучения(заочногообучения)(вт.ч.техническое)",
"обработкарезультатовтестированияпомодулю,подготовкааналитическойсправки",
"промежуточныйконтрольповариативномумодулю(проверказачетныхработ)",
"руководствостажировкойпопрограммамдополнительногопрофессиональногообразованияворганизацияхспроверкойотчетов",

SISPR/Controllers/LKController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SISPR.Models;
using System.Diagnostics;

namespace SISPR.Controllers
{
    public class LKController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public LKController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Profile()
        {
            return View();
        }

    }
}

SISPR/Controllers/UploadFileController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

using SISPR.Models;

namespace SISPR.Controllers
{
    public class UploadFileController : Controller
    {
        //ApplicationContext _context;

        //public UploadFileController(ApplicationContext context)
        //{
        //    _context = context;

        //}
        public IActionResult Index()
        {
            return View("UploadFile");
        }


        //public async void  AddFile(IFormFileCollection uploads)
        //{
        //    foreach (var uploadedFile in uploads)
        //    {
        //        // путь к папке Files
        //        string path = "/wwwroot/Files/" + uploadedFile.FileName;
        //        // сохраняем файл в папку Files в каталоге wwwroot
        //        using (var fileStream = new FileStream(Directory.GetCurrentDirectory() + path, FileMode.Create))
        //        {
        //            await uploadedFile.CopyToAsync(fileStream);
        //        }
        //        FileModel file = new FileModel { Name = uploadedFile.FileName, Path = path };
        //        //   _context.Files.Add(file);
        //    }
        //    // _context.SaveChanges();

           
        //}
        public async Task<string> AddFile(IFormFile upload)
        {
          
          
                // путь к папке Files
                string path = "/wwwroot/Files/" + upload.FileName;
                // сохраняем файл в папку Files в каталоге wwwroot
                using (var fileStream = new FileStream(Directory.GetCurrentDirectory() + path, FileMode.Create))
                {
                    await upload.CopyToAsync(fileStream);
                }

                FileModel file = new FileModel { Name = upload.FileName, Path = path };
             //   _context.Files.Add(file);
            
           // _context.SaveChanges();
          
            return path;
        }
    }
}

SISPR/Views/Shared/UploadFile.cshtml
<form asp-action="AddUTP" asp-controller="CheckUTPExcel" method="post" enctype="multipart/form-data">
    <input type="file" name="upload" /><br>
    <input type="submit" value="Загрузить" />
</form>

SISPR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"] - АППО (Автоматизированая платформа персонифицированного обучения Краснодарского края)</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/bootstrap-select.css" rel="stylesheet" />



    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />
</head>
<body class="theme_bg_grad">

    <canvas id="stars"></canvas>






    <nav class="navbar navbar-expand-lg navbar-light navbar1 text-white bg-nav align-items-start">
        <div class="container-fluid row justify-content-between ">
            <div class="col-4 me-auto">
                <a class="navbar-brand logo-nav " href="#"><img src="~/file/logo200.png" width="70" />ИРО КК</a>
            </div>
            <div class="col-8 text-end">
                <button class="navbar-toggler " type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Переключатель навигации">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse ms-auto" id="navbarTogglerDemo02">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">

                        <li class="nav-item">
                            <a asp-action="Profile" asp-controller="LK" class="nav-link btn btn-theme fs-3 text-white">
                                <i class="bi bi-person-square"></i> Профиль
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Login" asp-controller="Account" class="nav-link btn btn-theme fs-3 text-white">
                                <i class="bi bi-key"></i>
                                Войти
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>







    @* <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">СИСПР</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Приватность</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>*@
    <div class="container ">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - АППО (Автоматизированая платформа персонифицированного обучения Краснодарского края) - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

        <script src="~/js/jquery.maskedinput.min.js"></script>*@
    @*<script src="https://unpkg.com/vue@next"></script>
        <script src=" https://cdnjs.cloudflare.com/ajax/libs/trianglify/0.1.5/trianglify.min.js" asp-append-version="true"></script>
        <script src=" https://cdnjs.cloudflare.com/ajax/libs/d3/3.4.13/d3.min.js" asp-append-version="true"></script>*@


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>*@
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/jquery.maskedinput.min.js"></script>
    <script src="~/js/bootstrap-select.js"></script>
    <script src="~/js/defaults-ru_RU.js"></script>
    <script src="~/js/stars.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>