SISPR/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SISPR.Models;
using System.Diagnostics;
using Dadata;
using Dadata.Model;
using System.Threading.Tasks;
using System.Text.Json;
using SISPR.Models.DataBase.Basic.Location;

namespace SISPR.Controllers
{
    public class CourseController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public string token = "849df9cd46f8aa00925f2033914543026fe5af1f";
        public string secret = "366e5b7bd413da10837fd15f91c5120ff69289e1";
        public CourseController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }


        public IActionResult AddCourse()
        {


            return View();
        }


        async public Task<IActionResult> AdresAjax(string adr)
        {
            City city = new City();
            var api = new SuggestClientAsync(token);
            SuggestAddressRequest a = new SuggestAddressRequest(adr, 1)
            {
                from_bound = new AddressBound("city"),
                to_bound = new AddressBound("settlement"),
                /* locations = new[] { new Address() { area = "Кущевский" } }*/
            };
            var result = await api.SuggestAddress(a);
            for (int i = 0; i < 10 && result.suggestions.Count == 0; i++)
                result = await api.SuggestAddress(a);
            

            try
            {
                city.name = result.suggestions[0].data.city_with_type ?? result.suggestions[0].data.settlement_with_type;
                city.search_name = result.suggestions[0].data.city ?? result.suggestions[0].data.settlement;
                city.fias_code = result.suggestions[0].data.fias_code;
                //TODO
                string val = result.suggestions[0].value;
                if (result.suggestions[0].data.area == null)
                    city.mo_id = -10;
                if (result.suggestions[0].data.city_with_type == null && result.suggestions[0].data.area_with_type == null)
                    city.mo_id = -20;
            }
            catch
            {
                city.mo_id = -30;
            }


            return Json(city);
        }

        public IActionResult CreateRaspisan()
        {
            return View();
        }


    }
}

SISPR/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SISPR.Models;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;

namespace SISPR.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            ErrorViewModel model = new ErrorViewModel();
            model.RequestId = "Работай";
            return View("Index", model);
        }

        public IActionResult Profil()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SISPR/Controllers/LKController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SISPR.Models;
using System.Diagnostics;

namespace SISPR.Controllers
{
    public class LKController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public LKController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Profile()
        {
            return View();
        }

    }
}

SISPR/Controllers/UTPController.cs
using Dadata;
using Dadata.Model;
using Microsoft.AspNetCore.Cryptography.KeyDerivation;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SISPR.Controllers.Service;
using SISPR.Models.DataBase;
using SISPR.Models.DataBase.Basic.Location;
using SISPR.Models.DataBase.Basic.User;
using SISPR.Models.ViewModels;
using System.Threading.Tasks;

namespace SISPR.Controllers
{
    public class UTPController : Controller
    {
     

        public async Task<IActionResult> Index()
        {
                return View();
            
        }
        public async Task<IActionResult> Add()
        {
            return RedirectToAction("Index", "UploadFile");

        }
    }
}

SISPR/Views/Home/Index.cshtml
@model SISPR.Models.ErrorViewModel
@{
    ViewData["Title"] = "Главная";

}

<div class="text-center row">
    <h1 class="display-4">Добро пожаловать</h1>
    <p>на Портал педагога</p>
    <a asp-action="Index" asp-controller="UTP" class="a">УТП</a>
        <div class="row row-cols-1 row-cols-md-3 g-3">
            <div class="col">
                <div class="card ">
                    <a asp-action="AddCourse" asp-controller="Course" class="a">
                        <img src="~/file/b1.jpeg" width="400" height="200" class="card-img-top img-card-home" alt="...">
                        <div class="card-body">
                            <h5 class="card-title "><b>КУРСЫ</b></h5>
                            <p class="card-text text-black-100">Регистрация на курсы</p>
                        </div>
                    </a>
                    <div class="card-footer">
                        <small class="text-muted">Вы участвуете в <b>2х</b> курсах</small>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card ">
                    <img src="~/file/b1.jpeg" width="200" height="200" class="card-img-top img-card-home" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">ИОМ</h5>
                        <p class="card-text">Выша индивидуальная дорожная карта</p>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">Вам нужно выполнить <b>4 шага</b></small>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card ">
                    <img src="~/file/b3.png" width="200" height="200" class="card-img-top img-card-home" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Конкурсы</h5>
                        <p class="card-text">Принять участие в конкурсе</p>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">Вы не участвуете в конкурсе</small>
                    </div>
                </div>
            </div>
            <div class="col">


                <div class="card ">
                    @*<div id="polygon" class="card-img-top img-card-home" style="height:200px"></div>*@
                    <a asp-action="Profile" asp-controller="LK" class="a">
                        <img src="~/file/b1.jpeg" width="200" height="200" class="card-img-top img-card-home" alt="...">

                        <div class="card-body">
                            <h4 class="card-title">Личный кабинет</h4>
                            <p class="card-text text-black-100">Ваше портфолио и достижения</p>
                        </div>
                    </a>
                    <div class="card-footer">
                        <small class="text-muted">Необходимо загрузить данные</small>
                    </div>
                </div>


            </div>
            <div class="col">

                <div class="card ">
                    @*<div id="polygon" class="card-img-top img-card-home" style="height:200px"></div>*@
                    <img src="~/file/b1.jpeg" width="200" height="200" class="card-img-top img-card-home" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Основные ресурсы</h5>
                        <p class="card-text">Сайты</p>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">iro23.ru </small>
                    </div>
                </div>

            </div>
            <div class="col">

                <div class="card ">
                    @*<div id="polygon" class="card-img-top img-card-home" style="height:200px"></div>*@
                    <img src="~/file/b1.jpeg" width="200" height="200" class="card-img-top img-card-home" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Мероприятия</h5>
                        <p class="card-text">Семинары, вэбинары, конференции</p>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">iro23.ru </small>
                    </div>
                </div>

            </div>
        </div>
</div>
<div id="polygon1"></div>
<script src="~/js/three.min.js"></script>
@*<script src="~/js/zoom-polygon.js"></script>*@

SISPR/Views/Home/Profil.cshtml
@model SISPR.Models.ErrorViewModel
@{
    ViewData["Title"] = "Home Page";

}

<div class="col-12 shadow p-3 mb-5 bg-white rounded ">

    <div class="row">
        <div class="col-8">
            <h4>Основная информация</h4>
            <div class="row mb-3">
                <label for="inputEmail3" class="col-sm-3 col-form-label">Фамилия</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control inp-theme" id="inputEmail3">
                </div>
            </div>
            <div class="row mb-3">
                <label for="inputPassword3" class="col-sm-3 col-form-label">Имя</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control inp-theme" id="inputEmail3">
                </div>
            </div>
            <div class="row mb-3">
                <label for="inputPassword3" class="col-sm-3 col-form-label">Отчество</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control inp-theme" id="inputEmail3">
                </div>
            </div>

            <div class="row mb-3">
                <label for="inputPassword3" class="col-sm-3 col-form-label">Должность</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control inp-theme" id="inputEmail3">
                </div>
            </div>
            <div class="row mb-3">
                <label for="inputPassword3" class="col-sm-3 col-form-label">СНИЛС</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control inp-theme mask-snils" id="inputEmail3">
                </div>
                <script>
                    $('.mask-snils').mask('999-999-999 99');
                </script>
            </div>
            <div class="row mb-3">
                <label for="inputPassword3" class="col-sm-3 col-form-label">Телефон</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control inp-theme mask-phone" id="inputEmail3">
                </div>
                <script>
                    $('.mask-phone').mask('+7 (999) 999-99-99');
                </script>
            </div>
            <div class="row mb-3">
                <label for="inputPassword3" class="col-sm-3 col-form-label">E-mail</label>
                <div class="col-sm-9">
                    <input type="email" class="form-control inp-theme" id="inputEmail3">
                </div>
            </div>
        </div>
        <div class="col-4">
            <figure class="card info-bottom">
                <img src="~/file/profil1.png" class="col-12" />
                <figcaption>

                    <h5 class="text-center">Изменить фотографию</h5>


                </figcaption>
            </figure>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-8">
            <h4>Адресс и организация</h4>
            <div class="row mb-3">
                <label for="inputPassword3" class="col-sm-3 col-form-label">Регион</label>
                <div class="col-sm-9">
                    <select class="form-select inp-theme" aria-label="Регион" id="regionInput">
                        <option value="23">Краснодарский край</option>
                        <option value="69">Ростовская область</option>
                        <option value="26">Ставропольский край</option>
                    </select>
                </div>
            </div>
            <div class="row mb-3">
                <label for="inputPassword3" class="col-sm-3 col-form-label">МО</label>
                <div class="col-sm-9">
                    <select class="form-select inp-theme" aria-label="Муниципалитет" id="moInput">
                        <option value="23">Краснодар</option>
                        <option value="69">Сочи</option>
                        <option value="26">Кущевский район</option>
                    </select>
                </div>

            </div>

            <div class="row mb-3">
                <label for="inputPassword3" class="col-sm-3 col-form-label">Населенный пункт</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control inp-theme" id="cityInput" placeholder="Краснодар">
                </div>
            </div>
            @*</div>
                <div class="row m-2">*@
            <div class="row mb-3">
                <label class="col-sm-3 col-form-label" for="ooInput">Краткое наименование ОО</label>
                <div class="col-sm-9">
                    <input type="email" class="form-control inp-theme" id="ooInput" placeholder="СОШ №1">
                </div>

            </div>
        </div>
        <div class="col-4">
            <h4>Опции</h4>
            <ul id="yui_3_17_2_1_1626761899275_19"><li><span><a href="http://do.iro23.ru/report/log/user.php?id=5563&amp;course=1&amp;mode=today">Сегодняшние события</a></span></li><li><span><a href="http://do.iro23.ru/report/log/user.php?id=5563&amp;course=1&amp;mode=all">Все события</a></span></li><li><span><a href="http://do.iro23.ru/report/outline/user.php?id=5563&amp;course=1&amp;mode=outline">Краткий отчет</a></span></li><li><span><a href="http://do.iro23.ru/report/outline/user.php?id=5563&amp;course=1&amp;mode=complete">Полный отчет</a></span></li><li><span><a href="http://do.iro23.ru/report/stats/user.php?id=5563&amp;course=1">Статистика</a></span></li><li><span><a href="http://do.iro23.ru/report/usersessions/user.php">Сессии браузера</a></span></li><li><span><a href="http://do.iro23.ru/grade/report/overview/index.php?userid=5563&amp;id=1">Обзор оценок</a></span></li><li><span><a href="http://do.iro23.ru/course/user.php?mode=grade&amp;id=1&amp;user=5563">Оценка</a></span></li></ul>
        </div>
    </div>

    <fieldset class="row mb-3">
        <legend class="col-form-label col-sm-3 pt-0">Radios</legend>
        <div class="col-sm-9">
            <div class="form-check">
                <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios1" value="option1" checked>
                <label class="form-check-label" for="gridRadios1">
                    First radio
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios2" value="option2">
                <label class="form-check-label" for="gridRadios2">
                    Second radio
                </label>
            </div>
            <div class="form-check disabled">
                <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios3" value="option3" disabled>
                <label class="form-check-label" for="gridRadios3">
                    Third disabled radio
                </label>
            </div>
        </div>
    </fieldset>
    <div class="row mb-3">
        <div class="col-sm-9 offset-sm-2">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" id="gridCheck1">
                <label class="form-check-label" for="gridCheck1">
                    Example checkbox
                </label>
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Sign in</button>

</div>
<div id="polygon1"></div>
<script src="~/js/three.min.js"></script>
<script src="~/js/zoom-polygon.js"></script>